name: approval_tests
description: Approval Tests implementation in Dart. Inspired by ApprovalTests.
version: 0.0.4-dev
publish_to: https://pub.dev/packages/approval_tests
repository: https://github.com/K1yoshiSho/approval_tests_dart
homepage: https://github.com/K1yoshiSho/approval_tests_dart.git
issue_tracker: https://github.com/K1yoshiSho/approval_tests_dart/issues

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  test: ^1.25.4
  logger: ^2.2.0

dev_dependencies:
  lints: ^3.0.0

topics:
  - test
  - approval
  - approvals
  - tests
  - testing
  - approval-tests
  - verifier
  - verify