name: approvals_test
description: Approval Tests implementation in Dart. Inspired by ApprovalTests.
version: 0.0.4-dev
repository: https://github.com/K1yoshiSho/approval_tests_dart
homepage: https://github.com/K1yoshiSho/approval_tests_dart.git
issue_tracker: https://github.com/K1yoshiSho/approval_tests_dart/issues

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  test: ^1.25.4

dev_dependencies:
  lints: ^3.0.0
